title: Author support for The New England Journal of Statistics in Data Science journal
description: LaTeX related material for the manuscript preparation
show_downloads: true
theme: jekyll-theme-cayman